# Generated by Django 5.1.4 on 2025-02-24 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=500)),
                ('inclusive', models.CharField(max_length=500)),
                ('exclusive', models.CharField(max_length=500)),
                ('image1', models.ImageField(default='images/giraffe.jpg', upload_to='images/')),
                ('image2', models.ImageField(default='images/giraffe.jpg', upload_to='images/')),
                ('image3', models.ImageField(default='images/giraffe.jpg', upload_to='images/')),
                ('image4', models.ImageField(default='images/giraffe.jpg', upload_to='images/')),
                ('accomodation', models.FloatField(default=0)),
                ('transport', models.FloatField(default=0)),
                ('meals', models.FloatField(default=0)),
                ('others', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(choices=[('Mpesa', 'M'), ('Paypal', 'P')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('review', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('profile_photo', models.ImageField(default='images/giraffe.jpg', upload_to='images/')),
                ('reviewed_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('adult', models.IntegerField()),
                ('children', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('booked', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourapp.trip')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
