# Generated by Django 5.1.4 on 2025-02-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0002_alter_tripbooking_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripbooking',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='trip',
        ),
    ]
