# Generated by Django 5.1.4 on 2025-02-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0003_remove_tripbooking_booked_remove_tripbooking_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripbooking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourapp.trip'),
        ),
    ]
