# Generated by Django 5.1.4 on 2025-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0004_tripbooking_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(default='images/giraffe.jpg', upload_to='images/')),
                ('site', models.CharField(choices=[('Hotel', 'H'), ('Game Park', 'GP'), ('Musiem', 'M'), ('Lodgin', 'L'), ('Airport', 'A')], max_length=15)),
            ],
        ),
    ]
