# Generated by Django 5.1.4 on 2025-02-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0005_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desription', models.CharField(max_length=500)),
                ('hotel_photo', models.ImageField(default='images/giraffe.jpg', upload_to='images/')),
                ('price', models.FloatField()),
            ],
        ),
    ]
