# Generated by Django 5.1.4 on 2025-02-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0006_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='desription',
            new_name='description',
        ),
    ]
