# Generated by Django 5.1.4 on 2025-02-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0007_rename_desription_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_photo',
            field=models.ImageField(default='images/villarosa.webp', upload_to='images/'),
        ),
    ]
