# Generated by Django 5.1.4 on 2025-02-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0008_alter_hotel_hotel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_photo',
            field=models.ImageField(default='images/villarosa.jpg', upload_to='images/'),
        ),
    ]
