# Generated by Django 5.1.4 on 2025-02-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0010_hotel_latitude_hotel_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='latitude',
            new_name='hotel_latitude',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='longitude',
            new_name='hotel_longitude',
        ),
    ]
