# Generated by Django 5.1.4 on 2025-02-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0011_rename_latitude_hotel_hotel_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_longitude',
            new_name='longitude',
        ),
    ]
