# Generated by Django 5.1.4 on 2025-03-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0015_hotelbooking_hotel_hotelbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripbooking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
