# Generated by Django 5.1.4 on 2025-03-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0017_remove_tripbooking_paid_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booked_for',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
