# Generated by Django 5.1.4 on 2025-03-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0018_payment_booked_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='profile_photo',
            field=models.ImageField(default='images/user.png', upload_to='images/'),
        ),
    ]
