# Generated by Django 5.1.4 on 2025-03-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0021_staff_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='images/user.png', upload_to='images/'),
        ),
    ]
